### ISSUE TITLE
findOne is throwing an exception when the supplied id doesn't exist

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#375]
When I try `findOne` passing a non-existing id, it throws:

> TypeError: Cannot read property 'length' of null
>     at find.apply.then.results (/home/andrerpena/git/indiejobs/node_modules/massive/lib/queryable.js:115:16)
>     at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by andrerpena** [comment]
This doesn't happen if I use an object instead of the primary key.

I mean...

    db.foo.findOne(999) // throws
    db.foo.findOne({id: 999}) // does NOT throw
