### ISSUE TITLE
In scripts, parameters are not ignored when they are in a comment

### ISSUE THREAD

**Issue by asBrettisay** [dmfay/massive-js#382]
Node @ 8.0.0 and massive @3.0.0-rc1

It appears that scripts with a parameter in them, where the parameter is behind a comment, are not ignored.

`select * from airplanes`
returns:
```
planes [ anonymous { planeid: 1, planetype: '747', passengercount: 200 },
  anonymous { planeid: 2, planetype: '717', passengercount: 10 },
  anonymous { planeid: 3, planetype: '727', passengercount: 20 },
  anonymous { planeid: 4, planetype: '737', passengercount: 30 },
  anonymous { planeid: 5, planetype: '757', passengercount: 500 } ]
```

as does `select * from airplanes --where passengercount < 10`

However, `select * from airplanes --where passengercount < $1`
Will return `Error retrieving planes RangeError: Variable $1 out of range. Parameters array length: 0`

The expected behavior is that the parameter would be ignored, since it is behind a comment.

Full stack trace:
```
Error retrieving planes RangeError: Variable $1 out of range. Parameters array length: 0
    at query.replace.name (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/formatting.js:146:19)
    at String.replace (<anonymous>)
    at Object.array (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/formatting.js:133:22)
    at Object.$formatQuery [as formatQuery] (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/formatting.js:237:29)
    at Database.$query (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/query.js:112:41)
    at Database.<anonymous> (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/query.js:227:23)
    at config.$npm.connect.pool.then.db (/Users/Brett/DevMountain/projects/sql/mini-sql-node-massive/node_modules/pg-promise/lib/database.js:242:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by vitaly-t** [comment]
When you put such a query through the query-formatting engine:
```
select * from airplanes --where passengercount < $1
```
that engine will parse the string only for variables, not for comments.

Why do you have comments like this in your query in the first place? You really shouldn't. Maybe if you explain how this happened, I will be be able to advise how to deal with this.

**Comment by robconery** [comment]
LOL yeah that was something that was on the radar. This is a driver-level problem, we don't parse arguments in SQL strings - which I'm sure @dmfay will reply. At least I hope so!

**Comment by vitaly-t** [comment]
So, the example I was talking about would be something like this:

```js
// create it just once:
var sql = new massive.pgp.QueryFile('./path/my-file.sql', {minify: true});

// and then use it:
massive.run(sql, parameters).then(...).catch(...)
```

**Comment by dmfay** [comment]
Massive loads query files in the /db directory, but right now it's not using pg-promise's QueryFiles to do that -- just plain old `fs.readFile`. That can change though, and it sounds like `minify` should take care of it!

**Comment by asBrettisay** [comment]
@vitaly-t At our coding school, we teach Massive, and use comments like this to help guide the teaching experience. Thanks so much for addressing this!
