### ISSUE TITLE
Enable table configuration

### ISSUE THREAD

**Issue by jaimesangcap** [dmfay/massive-js#501]
It seems that the table generation is hard coded in the script file `lib/scripts/document-table.sql`. Is there any plan of making it configurable? For example changing the `id` from `serial` to `uuid` or adding `updated_at` column. If yes, may I know what at your thoughts about it, maybe I can use them as starting point to play with.

**Comment by dmfay** [comment]
I would _love_ to have runtime-configurable document tables, and a uuid key option and `updated_at` are only the start of where that could go. It's pretty far down my priority list at the moment so if you want to take a stab at it, be my guest!

**Comment by jaimesangcap** [comment]
Would you mind if I ask I what are on your list now?

**Comment by dmfay** [comment]
Right now I'm adding the missing idiomatic JSON traversal to find functions' `options.columns` -- actually deprecating that in favor of combining new `options.fields` & `options.exprs` to avoid having to cut v5 already, since the field parser adds quotes which break scalar operations like arithmetic or string concatenation.

Next up is revising how tables views functions and scripts are structured on the `Database` object to use a more compositional approach. This will allow (for example) having a `company` table, a `company` schema, and a `company` subdirectory in your script files all at the same time (#387) and also hopefully make some further-in-the-future things easier, like juggling multiple connection pools.

**Comment by jaimesangcap** [comment]
Cool, I think you're using database views and scripts quiet heavily?

 For customizing the table, I'm thinking of adding `table/documents` property to the database `options`. options will have default settings for all documents, but enable overriding per document using the document name as the `property/key`. Then maybe adjust the `document-table.sql` depending on the options.

```
options.documents['tasks'] = {
// some key => value settings
}
```

What do you think? 

PS: I haven't really done any open source project before and maybe this project is not a good place for me to start with as a newbie, please let me know.

**Comment by dmfay** [comment]
I got five people who'd never touched open source before to make their first commits breaking apart some of Massive's test schemas at a workshop just last month so no worries there :laughing: This is a little more involved so it might take a bit of back&forth to get this done but I'm game if you are.

Setting the defaults in the database `options` sounds good. Overrides should happen as close to the point of creating document tables as possible, though: if you're generating document tables dynamically, the name may not be consistent or predictable. So I'd do that as another argument to `createDocumentTable` itself instead of in the `options`.

**Comment by jaimesangcap** [comment]
great! I still have more code reading to do though before getting started. And some tests are failing on my machine. I'm using the docker `dmfay/pg-massive`

```
443 passing (5s)
  2 pending
  5 failing

  1) connecting variations connects with undefined connections using default configuration:
     error: role "jaime" does not exist
      at Connection.parseE (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:546:11)
      at Connection.parseMessage (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:371:19)
      at Socket.<anonymous> (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:114:22)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
      at Socket.Readable.push (_stream_readable.js:211:10)
      at TCP.onread (net.js:585:20)

  2) connecting variations connects with empty connection block using default configuration:
     error: role "jaime" does not exist
      at Connection.parseE (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:546:11)
      at Connection.parseMessage (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:371:19)
      at Socket.<anonymous> (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:114:22)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
      at Socket.Readable.push (_stream_readable.js:211:10)
      at TCP.onread (net.js:585:20)

  3) connecting variations connects with empty connection strings using default configuration:
     error: role "jaime" does not exist
      at Connection.parseE (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:546:11)
      at Connection.parseMessage (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:371:19)
      at Socket.<anonymous> (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:114:22)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
      at Socket.Readable.push (_stream_readable.js:211:10)
      at TCP.onread (net.js:585:20)

  4) reload "before all" hook:
     error: role "jaime" does not exist
      at Connection.parseE (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:546:11)
      at Connection.parseMessage (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:371:19)
      at Socket.<anonymous> (/Users/jaime/Projects/massive-js/node_modules/pg/lib/connection.js:114:22)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
      at Socket.Readable.push (_stream_readable.js:211:10)
      at TCP.onread (net.js:585:20)

  5) reload "after all" hook:
     TypeError: Cannot read property 'instance' of undefined
      at Context.after (/Users/jaime/Projects/massive-js/test/database/reload.js:16:17)
      at callFn (/Users/jaime/Projects/massive-js/node_modules/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/Users/jaime/Projects/massive-js/node_modules/mocha/lib/runnable.js:216:7)
      at Hook.Runnable.run (/Users/jaime/Projects/massive-js/node_modules/co-mocha/lib/co-mocha.js:43:16)
      at next (/Users/jaime/Projects/massive-js/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/Users/jaime/Projects/massive-js/node_modules/mocha/lib/runner.js:276:5)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by dmfay** [comment]
Connect and reload tests are kind of screwy because you have to have infrastructure in place to support alternate connection parameters -- just ignore those for now.

**Comment by dmfay** [comment]
Those connect/reload tests should pass now if you pull the master branch.

**Comment by dmfay** [comment]
We've covered at least the obvious bases here.
