### ISSUE TITLE
find using 'body #>>' no longer works in massive > 2.x

### ISSUE THREAD

**Issue by ludvigsen** [dmfay/massive-js#609]
Hi!

I'm trying to go from massive 2.x to the latest version. So far most things have been straight forward, so good job!

I have one issue though, when using a syntax for find which worked previously i get this error:
```
ERROR:  TypeError: Cannot read property 'mutator' of undefined
    at Function.tableGenerator (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/statement/where.js:16:25)
    at _.reduce (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/statement/where.js:164:38)
    at /Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:914:11
    at /Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:3010:24)
    at /Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:4894:18
    at baseReduce (/Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/Users/marius/vimond/vcc-curation/node_modules/massive/node_modules/lodash/lodash.js:9681:14)
    at generateConjunction (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/statement/where.js:139:12)
    at module.exports (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/statement/where.js:204:23)
    at new Select (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/statement/select.js:103:18)
    at Writable.Readable.find (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/readable.js:78:24)
    at Writable.Readable.findOne (/Users/marius/vimond/vcc-curation/node_modules/massive/lib/readable.js:108:15)
....
```

This is the exact statement I'm trying to execute:
`db.curation[table].find({ 'body #>> \'{listId}\'': 'test2', 'active': 'true'});`.

Is there something I'm missing?

**Comment by dmfay** [comment]
That should still work in v3, but I wrote a proper JSON path parser for v4 and up. So you need to issue `db.curation[table].find({ 'body.listId': 'test2', 'active': true });` instead of using the Postgres pathing operators. Array indices work how you'd expect coming from JS too.

**Comment by ludvigsen** [comment]
Oh, my bad, I only tested using latest, and assumed it was like this in everything above 2.x.

Your suggestion works like a charm though, thanks for the quick reply!
